language: ruby
bundler_args: --without doc
rvm:
  - 2.3.8
  - 2.6.3
before_install:
  - sudo apt-get install -qq libmagic-dev graphicsmagick tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng tesseract-ocr-spa pdftk libreoffice poppler-utils poppler-data ghostscript
script: bundle exec rake test
